name: flutter_app

environment:
  sdk: '^3.8.0'

flutter:
  assets:
    - .env
    - assets/documents.db

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  sqflite: ^2.3.0
  path: ^1.8.0